# Generated by Django 5.2.6 on 2025-09-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/previews/'),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='file',
            field=models.FileField(upload_to='uploads/originals/'),
        ),
    ]
